resolver: lts-12.0
flags: {}

packages:
- reinforce
- reinforce-algorithms
- reinforce-environments
- reinforce-environments-gym
- reinforce-zoo
- reinforce-gridworlds
- location: ./gym-http-api/binding-hs

extra-deps:
- reactive-banana-1.2.0.0
- termbox-0.1.0
- termbox-banana-0.1.0

extra-lib-dirs:
- /usr/local/lib/
- /compat/linux/lib/

extra-include-dirs:
- /usr/local/include/

nix:
  enable: true
  shell-file: shell.nix
