resolver: lts-12.0
flags: {}

packages:
- reinforce
- reinforce-algorithms
- reinforce-environments
- reinforce-environments-gym
- reinforce-zoo

# - reinforce-gridworld
# 
# extra-deps:
# - reactive-banana-1.2.0.0

extra-lib-dirs:
- /usr/local/lib/
- /compat/linux/lib/

extra-include-dirs:
- /usr/local/include/
