name:        reinforce-gridworlds
version:     0.0.1.0
synopsis:    Building gridworlds for reinforcement learning
category:    Reinforcement learning, Simulations
author:      Sam Stites, Sentenai Inc.
maintainer:  sam@sentenai.com
github:      Sentenai/reinforce/reinforce-gridworld
license:     BSD3
copyright:   2017 Sentenai, Inc.
ghc-options: -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists

description: See <https://github.com/Sentenai/reinforce README.md>.
    @reinforce@ is a library which exports an OpenAI-gym-like
    typeclass, @MonadEnv@, with both an interface to the
    <https://github.com/openai/gym-http-api/ gym-http-api>, as well as
    haskell-native environments which provide a substantial speed-up to the
    http-server interface.

    This is an environment-first library, with basic reinforcment
    learning algorithms being developed on branches in subpackages (see
    <https://github.com/Sentenai/reinforce#development-and-milestones
    Development and Milestones>). @reinforce@ is currently an "alpha"
    release since it still needs some work defining some formal structures
    around what state-spaces and action-spaces should look like,
    however haskell's typesystem is expressive enough that this seems to be
    more of a "nice-to-have."

    It's in active development and has some beginner-friendly contributions -
    from porting new gym environments to implementing new algorithms.


default-extensions:
  - MultiParamTypeClasses
  - OverloadedStrings
  - LambdaCase
  - TypeFamilies


library:
  source-dirs: src
  dependencies:
    - base               >= 4.9 && < 5.0
    # transformers
    # mtl
    # mwc-random
    # statistics
    # safe-exceptions
    - hashable
    - reactive-banana
    - unordered-containers
    - reinforce
    # text
    # vector

executables:
  demo:
    source-dirs: app
    main: Main.hs
    dependencies:
      - base
      - reinforce-gridworlds
      - reactive-banana


